-- ORBITA CREATIVE - leads table
-- Rulează în Supabase > SQL Editor > New query

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  project_type text not null,
  budget text not null default 'Nu știu încă',
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now(),

  constraint leads_status_check
    check (status in ('new', 'contacted', 'won', 'lost')),

  constraint leads_name_length
    check (char_length(trim(name)) between 2 and 120),

  constraint leads_email_length
    check (char_length(trim(email)) between 5 and 254),

  constraint leads_message_length
    check (char_length(trim(message)) between 3 and 5000)
);

alter table public.leads enable row level security;

-- Închidem accesul implicit și permitem publicului DOAR INSERT.
revoke all on table public.leads from anon;
revoke all on table public.leads from authenticated;

grant insert on table public.leads to anon;

-- Vizitatorii site-ului pot trimite o cerere, dar nu pot citi,
-- modifica sau șterge cererile existente.
drop policy if exists "Public can submit ORBITA leads" on public.leads;

create policy "Public can submit ORBITA leads"
on public.leads
for insert
to anon
with check (
  char_length(trim(name)) between 2 and 120
  and char_length(trim(email)) between 5 and 254
  and position('@' in email) > 1
  and char_length(trim(message)) between 3 and 5000
  and project_type in (
    'Invitație digitală de nuntă',
    'Invitație digitală de botez',
    'Website pentru business',
    'Landing page',
    'Proiect custom'
  )
  and budget in (
    'Nu știu încă',
    'Sub 500 lei',
    '500 – 1.000 lei',
    '1.000 – 2.500 lei',
    '2.500 – 5.000 lei',
    'Peste 5.000 lei'
  )
);
