import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  launchHandoff: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 140,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  launchMark: {
    width: 78,
    height: 78,
    borderRadius: 26,
    backgroundColor: "#17132b",
    borderWidth: 1,
    borderColor: "#7458ee",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#7458ee",
    shadowOpacity: 0.24,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  launchMarkText: {
    color: "#ffffff",
    fontWeight: "900",
    letterSpacing: -1.6,
    fontSize: 23,
  },
  launchTitle: {
    marginTop: 20,
    fontSize: 21,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  launchSubtitle: {
    marginTop: 7,
    fontSize: 12,
    textAlign: "center",
  },
  launchSpinner: {
    marginTop: 18,
  },
  networkNotice: {
    position: "absolute",
    top: 8,
    left: 18,
    right: 18,
    zIndex: 120,
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 14,
    paddingVertical: 8,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  networkNoticeOffline: {
    backgroundColor: "rgba(57,24,31,0.96)",
    borderColor: "rgba(255,123,123,0.34)",
  },
  networkNoticeOnline: {
    backgroundColor: "rgba(18,60,49,0.96)",
    borderColor: "rgba(111,224,174,0.34)",
  },
  networkNoticeDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  networkNoticeText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.1,
  },
  header: {
    minHeight: 66,
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brandRow: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 10 },
  brandCopy: { flex: 1, minWidth: 0 },
  mark: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#17132b",
    borderWidth: 1,
    borderColor: "#6e56cf",
    alignItems: "center",
    justifyContent: "center",
  },
  markText: { color: "#ffffff", fontWeight: "800", letterSpacing: -1, fontSize: 14 },
  brand: { fontSize: 14, fontWeight: "800", letterSpacing: 1.6 },
  subtitle: { fontSize: 10, marginTop: 2 },
  status: { flexShrink: 0, marginLeft: 10, borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 },
  statusOnline: { backgroundColor: "#123c31" },
  statusOffline: { backgroundColor: "#4a2327" },
  statusLoading: { backgroundColor: "#332b55" },
  statusText: { color: "#ffffff", fontWeight: "800", fontSize: 9, letterSpacing: 0.8 },
  content: { flex: 1 },
  loader: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    zIndex: 10,
  },
  loaderTitle: { fontSize: 20, fontWeight: "800", marginTop: 16, textAlign: "center" },
  loaderText: { fontSize: 13, lineHeight: 19, marginTop: 7, textAlign: "center", maxWidth: 330 },
  retryButton: { marginTop: 18, backgroundColor: "#7458ee", borderRadius: 12, paddingHorizontal: 18, paddingVertical: 11 },
  retryText: { color: "#ffffff", fontWeight: "700" },
  toolbar: {
    minHeight: 62,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-around",
    paddingHorizontal: 4,
  },
  toolButton: { flex: 1, alignItems: "center", justifyContent: "center", minHeight: 58 },
  toolButtonPressed: { opacity: 0.55 },
  toolIcon: { fontSize: 23, lineHeight: 25, fontWeight: "600" },
  toolHint: { fontSize: 9, marginTop: 2, fontWeight: "600" },
  disabled: { opacity: 0.35 },
  privacyShield: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 100,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  shieldMark: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: "#17132b",
    borderWidth: 1,
    borderColor: "#6e56cf",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  shieldMarkText: {
    color: "#ffffff",
    fontWeight: "900",
    letterSpacing: -1.5,
    fontSize: 22,
  },
  shieldTitle: { fontSize: 22, fontWeight: "800", textAlign: "center" },
  shieldText: {
    maxWidth: 320,
    marginTop: 8,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  unlockButton: {
    marginTop: 22,
    minWidth: 150,
    borderRadius: 14,
    backgroundColor: "#7458ee",
    paddingHorizontal: 22,
    paddingVertical: 13,
    alignItems: "center",
  },
  unlockText: { color: "#ffffff", fontWeight: "800" },
  shieldSpinner: { marginTop: 22 },
});
