create table public.project_requests (
  id uuid primary key default gen_random_uuid(),
  request_no bigint generated by default as identity unique not null,
  organization_id uuid null references public.organizations(id) on delete set null,
  plan_id text null check (plan_id is null or plan_id in ('start','business','pro')),
  payment_mode text not null check (payment_mode in ('subscription','full_payment','custom_quote')),
  status text not null default 'submitted' check (status in ('submitted','qualified','quoted','payment_pending','converted','closed')),
  company_name text null,
  contact_name text not null,
  email text not null,
  phone text null,
  project_title text not null,
  project_details text not null,
  source text not null default 'public_site',
  privacy_accepted_at timestamptz not null,
  marketing_consent boolean not null default false,
  quoted_amount_minor bigint null check (quoted_amount_minor is null or quoted_amount_minor >= 0),
  quoted_currency text null,
  payment_reference text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.project_requests enable row level security;

revoke all on table public.project_requests from anon, authenticated;
grant select, insert, update, delete on table public.project_requests to service_role;
grant usage, select on sequence public.project_requests_request_no_seq to service_role;

create index project_requests_created_at_idx on public.project_requests (created_at desc);
create index project_requests_status_idx on public.project_requests (status, created_at desc);
create index project_requests_email_idx on public.project_requests (lower(email));

comment on table public.project_requests is
  'Public ORBYVEN commercial requests. Server/service-role only; no direct client policies.';
